export const JobsList = [
	{
		id: 1,
		nomeEmpresa: 'Base Brasil',
		funcao: 'Web Designer',
		periodo: '1998 a 2002',
		habilidades: ['HTML', 'JavaScript', 'Photoshop', 'Corel Draw', 'Flash'],
		descricao:
			'Como Web Designer tinha a responsabilidade na edição e tratamento de imagens. Depois passei a desenvolver sites para diversos projetos e clientes atuando...',
	},
	{
		id: 2,
		nomeEmpresa: 'Grupo Store',
		funcao: 'Web Designer',
		periodo: '1998 a 2002',
		habilidades: ['HTML', 'JavaScript', 'Photoshop', 'Corel Draw'],
		descricao:
			'Minha trajetória no Grupo Store começou como Web Master e Designer UI/UX. Era responsável pelo protótipo, desenvolvimento e manutenção dos sites corporativos para as cinco empresas, todos desenvolvidos em HTML, CSS, JavaScript, JQuery, Flash e também...',
	},
	{
		id: 3,
		nomeEmpresa: 'Estec Tecnologia',
		funcao: 'Web Designer',
		periodo: '1998 a 2002',
		habilidades: ['HTML', 'JavaScript', 'Photoshop', 'Corel Draw'],
		descricao:
			'Fui convidado para participar do desenvolvimento de um novo sistema para o mercado de PME com foco na gestão e digitalização de documentos chamado e2Content e também em uma plataforma para avaliação de alunos do...',
	},
	{
		id: 4,
		nomeEmpresa: 'Doce Affetto',
		funcao: 'Web Designer',
		periodo: '1998 a 2002',
		habilidades: [
			'ReactJs | NextJs',
			'Typescript | JavaScript',
			'CSS3 | Tailwind',
			'Git | GitHub | Vercel',
			'Design UI/UX',
			'Integromat',
			'Analytics',
			'Figma',
			'Illustrator',
			'Photoshop',
			'Adobe Premiere',
		],
		descricao:
			'Fui responsável pelo desenvolvimento e manutenção das páginas de lançamento de produtos do <span>e-commerce e lançamentos sazonais</span>, em React e NextJs. <p>Cuidava da estratégia de SEO, Ranking Page e demais otimizações (Tag Manager, Analytics...',
	},
	{
		id: 5,
		nomeEmpresa: 'Chef Joice Rodrigues',
		funcao: 'Front-End Developer (Freelancers)',
		periodo: '2020 - 2022',
		habilidades: [
			'ReactJs | NextJs',
			'Typescript | JavaScript',
			'Jest',
			'Cypress',
			'Tailwind | Styled Components',
			'SCSS',
			'Git | GitHub | Vercel',
			'Design UI/UX',
			'Figma',
			'Integromat',
			'Analytics',
		],
		descricao:
			'Fui responsável pelo desenvolvimento das páginas e sites dos lançamento dos cursos. Envolvendo análise, documentação e desenvolvimento da <span>plataforma dos alunos</span> para gestão...',
	},
	{
		id: 6,
		nomeEmpresa: 'Trinca',
		funcao: 'Front-End Developer',
		periodo: '2023 (atual)',
		habilidades: [
			'ReactJs',
			'NextJs',
			'Typescript | JavaScript',
			'Jest',
			'Tailwind',
			'Styled Components',
		],
		descricao: '',
	},
]
